// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("Department")]
    public class DepartmentController : ControllerBase {
        
        private IDepartmentBuilder _builder;
        
        public DepartmentController(IDepartmentBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<DepartmentModel>> GetDepartments() {

            return await _builder.GetDepartments()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(DepartmentModel.DepartmentID));
            propNames.Add(nameof(DepartmentModel.Name));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<DepartmentModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetDepartments()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{departmentID}")]
        public async Task<ActionResult> GetDepartment_ByDepartmentID(short departmentID) {

             var response = await _builder.GetDepartment_ByDepartmentID(departmentID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddDepartment([FromBody]DepartmentModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddDepartment(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddDepartment)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetDepartment_ByDepartmentID", new {departmentID = ((DepartmentModel)response.Model).DepartmentID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateDepartment([FromBody]DepartmentModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateDepartment(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateDepartment)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{departmentID}")]
        public async Task<ActionResult> DeleteDepartment(short departmentID) {

            var response = await _builder.DeleteDepartment(departmentID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteDepartment)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

