// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("EmployeeDepartmentHistory")]
    public class EmployeeDepartmentHistoryController : ControllerBase {
        
        private IEmployeeDepartmentHistoryBuilder _builder;
        
        public EmployeeDepartmentHistoryController(IEmployeeDepartmentHistoryBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<EmployeeDepartmentHistoryModel>> GetEmployeeDepartmentHistories() {

            return await _builder.GetEmployeeDepartmentHistories()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(EmployeeDepartmentHistoryModel.BusinessEntityID));
            propNames.Add(nameof(EmployeeDepartmentHistoryModel.DepartmentID));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<EmployeeDepartmentHistoryModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetEmployeeDepartmentHistories()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}/{startDate}/{departmentID}/{shiftID}")]
        public async Task<ActionResult> GetEmployeeDepartmentHistory_ByBusinessEntityIDStartDateDepartmentIDShiftID(int businessEntityID, System.DateTime startDate, short departmentID, byte shiftID) {

             var response = await _builder.GetEmployeeDepartmentHistory_ByBusinessEntityIDStartDateDepartmentIDShiftID(businessEntityID, startDate, departmentID, shiftID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetEmployeeDepartmentHistory_ByBusinessEntityID/{businessEntityID}")]
        public async Task<IList<EmployeeDepartmentHistoryModel>> GetEmployeeDepartmentHistory_ByBusinessEntityID(int businessEntityID) {

            return await _builder.GetEmployeeDepartmentHistory_ByBusinessEntityID(businessEntityID)?.ToListAsync();
        }
        
        [HttpGet("GetEmployeeDepartmentHistory_ByDepartmentID/{departmentID}")]
        public async Task<IList<EmployeeDepartmentHistoryModel>> GetEmployeeDepartmentHistory_ByDepartmentID(short departmentID) {

            return await _builder.GetEmployeeDepartmentHistory_ByDepartmentID(departmentID)?.ToListAsync();
        }
        
        [HttpGet("GetEmployeeDepartmentHistory_ByShiftID/{shiftID}")]
        public async Task<IList<EmployeeDepartmentHistoryModel>> GetEmployeeDepartmentHistory_ByShiftID(byte shiftID) {

            return await _builder.GetEmployeeDepartmentHistory_ByShiftID(shiftID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddEmployeeDepartmentHistory([FromBody]EmployeeDepartmentHistoryModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddEmployeeDepartmentHistory(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddEmployeeDepartmentHistory)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetEmployeeDepartmentHistory_ByBusinessEntityIDStartDateDepartmentIDShiftID", new {businessEntityID = ((EmployeeDepartmentHistoryModel)response.Model).BusinessEntityID, startDate = ((EmployeeDepartmentHistoryModel)response.Model).StartDate, departmentID = ((EmployeeDepartmentHistoryModel)response.Model).DepartmentID, shiftID = ((EmployeeDepartmentHistoryModel)response.Model).ShiftID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateEmployeeDepartmentHistory([FromBody]EmployeeDepartmentHistoryModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateEmployeeDepartmentHistory(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateEmployeeDepartmentHistory)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}/{startDate}/{departmentID}/{shiftID}")]
        public async Task<ActionResult> DeleteEmployeeDepartmentHistory(int businessEntityID, System.DateTime startDate, short departmentID, byte shiftID) {

            var response = await _builder.DeleteEmployeeDepartmentHistory(businessEntityID, startDate, departmentID, shiftID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteEmployeeDepartmentHistory)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

