// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("Employee")]
    public class EmployeeController : ControllerBase {
        
        private IEmployeeBuilder _builder;
        
        public EmployeeController(IEmployeeBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<EmployeeModel>> GetEmployees() {

            return await _builder.GetEmployees()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(EmployeeModel.BusinessEntityID));
            propNames.Add(nameof(EmployeeModel.NationalIDNumber));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<EmployeeModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetEmployees()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{businessEntityID}")]
        public async Task<ActionResult> GetEmployee_ByBusinessEntityID(int businessEntityID) {

             var response = await _builder.GetEmployee_ByBusinessEntityID(businessEntityID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddEmployee([FromBody]EmployeeModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddEmployee(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddEmployee)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetEmployee_ByBusinessEntityID", new {businessEntityID = ((EmployeeModel)response.Model).BusinessEntityID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateEmployee([FromBody]EmployeeModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateEmployee(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateEmployee)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{businessEntityID}")]
        public async Task<ActionResult> DeleteEmployee(int businessEntityID) {

            var response = await _builder.DeleteEmployee(businessEntityID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteEmployee)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

