// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("JobCandidate")]
    public class JobCandidateController : ControllerBase {
        
        private IJobCandidateBuilder _builder;
        
        public JobCandidateController(IJobCandidateBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<JobCandidateModel>> GetJobCandidates() {

            return await _builder.GetJobCandidates()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(JobCandidateModel.JobCandidateID));
            propNames.Add(nameof(JobCandidateModel.BusinessEntityID));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<JobCandidateModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetJobCandidates()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{jobCandidateID}")]
        public async Task<ActionResult> GetJobCandidate_ByJobCandidateID(int jobCandidateID) {

             var response = await _builder.GetJobCandidate_ByJobCandidateID(jobCandidateID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpGet("GetJobCandidate_ByBusinessEntityID/{businessEntityID}")]
        public async Task<IList<JobCandidateModel>> GetJobCandidate_ByBusinessEntityID(int businessEntityID) {

            return await _builder.GetJobCandidate_ByBusinessEntityID(businessEntityID)?.ToListAsync();
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddJobCandidate([FromBody]JobCandidateModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddJobCandidate(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddJobCandidate)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetJobCandidate_ByJobCandidateID", new {jobCandidateID = ((JobCandidateModel)response.Model).JobCandidateID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateJobCandidate([FromBody]JobCandidateModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateJobCandidate(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateJobCandidate)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{jobCandidateID}")]
        public async Task<ActionResult> DeleteJobCandidate(int jobCandidateID) {

            var response = await _builder.DeleteJobCandidate(jobCandidateID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteJobCandidate)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

