// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using InstantHelper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Controllers {
    
    
    // Uncomment the following line to use an API Key; change the value of the key in appSetting (X-API-Key)
    // [ApiKey()]
    [Route("Shift")]
    public class ShiftController : ControllerBase {
        
        private IShiftBuilder _builder;
        
        public ShiftController(IShiftBuilder builder) {
            _builder = builder;
        }
        
        [HttpGet("")]
        public async Task<IList<ShiftModel>> GetShifts() {

            return await _builder.GetShifts()?.ToListAsync();
        }
        
        [HttpGet("Display")]
        public IList<ExpandoObject> GetDisplayModels() {
            //List all model properties that should be displayed
            //Here only a couple have been added as an example
            var propNames = new List<string>();
            propNames.Add(nameof(ShiftModel.ShiftID));
            propNames.Add(nameof(ShiftModel.Name));

            return _builder.GetDisplayModels(propNames);
        }
        
        [HttpGet("Paged")]
        public async Task<IPagedList<ShiftModel>> Paged(int pageIndex, int pageSize) {

            var models = await _builder.GetShifts()?.ToListAsync();

            return models.ToPagedList(pageIndex, pageSize, 0, models.Count);
        }
        
        [HttpGet("{shiftID}")]
        public async Task<ActionResult> GetShift_ByShiftID(byte shiftID) {

             var response = await _builder.GetShift_ByShiftID(shiftID);
            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return Ok(response.Model);
        }
        
        [HttpPost("")]
        public async Task<ActionResult> AddShift([FromBody]ShiftModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }

            var response = await _builder.AddShift(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(AddShift)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return CreatedAtAction("GetShift_ByShiftID", new {shiftID = ((ShiftModel)response.Model).ShiftID}, response.Model);
        }
        
        [HttpPut("")]
        public async Task<ActionResult> UpdateShift([FromBody]ShiftModel model) {

            if (!ModelState.IsValid) {
              return BadRequest(ModelState);
            }
            var response = await _builder.UpdateShift(model);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(UpdateShift)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
        
        [HttpDelete("{shiftID}")]
        public async Task<ActionResult> DeleteShift(byte shiftID) {

            var response = await _builder.DeleteShift(shiftID);
            if (response.ErrorMessage != null) {
              return BadRequest($"Error for {nameof(DeleteShift)}; {response.ErrorMessage}");
            }

            if (response.RequestMessage != null) {
              return BadRequest(response.RequestMessage);
            }

            return StatusCode(response.StatusCode);
        }
    }
}

