// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using HumanResourcesAPI.Entities;
using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Services {
    
    
    public class EmployeePayHistoryBuilder : IEmployeePayHistoryBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public EmployeePayHistoryBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<EmployeePayHistory, EmployeePayHistoryModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<EmployeePayHistoryModel>(entity);
            }
        }
        
        public IQueryable<EmployeePayHistoryModel> GetEmployeePayHistories() {
            return _entities.EmployeePayHistories.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.EmployeePayHistories.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetEmployeePayHistory_ByBusinessEntityIDRateChangeDate(int businessEntityID, System.DateTime rateChangeDate) {
          var query = await Search(_entities.EmployeePayHistories, x => x.BusinessEntityID == businessEntityID&& x.RateChangeDate == rateChangeDate).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; EmployeePayHistory with businessEntityID, rateChangeDate = '{businessEntityID}', '{rateChangeDate}' doesn't exist." }; 
            }
        }
        
        public IQueryable<EmployeePayHistoryModel> GetEmployeePayHistory_ByBusinessEntityID(int businessEntityID) {

          var query = Search(_entities.EmployeePayHistories, x => x.BusinessEntityID == businessEntityID).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddEmployeePayHistory(EmployeePayHistoryModel model) {
            var matchBusinessEntityID = _entities.Employees.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
            if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.BusinessEntityID) + " '{model.BusinessEntityID}' doesn't exist in the system."}; 
            }

           try
           {
                 var entity = _mapper.Map<EmployeePayHistory>(model);
                _entities.EmployeePayHistories.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("EmployeePayHistory added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new EmployeePayHistoryModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateEmployeePayHistory(EmployeePayHistoryModel model) {

          var query = Search(_entities.EmployeePayHistories, x =>  x.BusinessEntityID == model.BusinessEntityID && x.RateChangeDate == model.RateChangeDate);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("EmployeePayHistory with _businessEntityID, _rateChangeDate = '{0}', '{1}' doesn't exist.",model.BusinessEntityID, model.RateChangeDate)}; 
            }
            var matchBusinessEntityID = _entities.Employees.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
            if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse { RequestMessage = "Foreign Key Violation; " + nameof(model.BusinessEntityID) + string.Format("BusinessEntityID = '{0}' doesn't exist in the system.", model.BusinessEntityID)}; 
            }

           try
           {
            EmployeePayHistory entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("EmployeePayHistory update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteEmployeePayHistory(int businessEntityID, System.DateTime rateChangeDate) {
          var query = Search(_entities.EmployeePayHistories, x => x.BusinessEntityID == businessEntityID&& x.RateChangeDate == rateChangeDate);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("EmployeePayHistory with _businessEntityID, _rateChangeDate = '{0}', '{1}' doesn't exist.",businessEntityID, rateChangeDate)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.EmployeePayHistories.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("EmployeePayHistory deleted with values: '{0}'", JsonConvert.SerializeObject(new EmployeePayHistoryModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<EmployeePayHistory> Search(IQueryable<EmployeePayHistory> query, Expression<Func<EmployeePayHistory, bool>> filter) {
            return query.Where(filter);
        }
    }
}

