// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using HumanResourcesAPI.Entities;
using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Services {
    
    
    public class EmployeeDepartmentHistoryBuilder : IEmployeeDepartmentHistoryBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public EmployeeDepartmentHistoryBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<EmployeeDepartmentHistory, EmployeeDepartmentHistoryModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<EmployeeDepartmentHistoryModel>(entity);
            }
        }
        
        public IQueryable<EmployeeDepartmentHistoryModel> GetEmployeeDepartmentHistories() {
            return _entities.EmployeeDepartmentHistories.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.EmployeeDepartmentHistories.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetEmployeeDepartmentHistory_ByBusinessEntityIDStartDateDepartmentIDShiftID(int businessEntityID, System.DateTime startDate, short departmentID, byte shiftID) {
          var query = await Search(_entities.EmployeeDepartmentHistories, x => x.BusinessEntityID == businessEntityID&& x.StartDate == startDate&& x.DepartmentID == departmentID&& x.ShiftID == shiftID).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; EmployeeDepartmentHistory with businessEntityID, startDate, departmentID, shiftID = '{businessEntityID}', '{startDate}', '{departmentID}', '{shiftID}' doesn't exist." }; 
            }
        }
        
        public IQueryable<EmployeeDepartmentHistoryModel> GetEmployeeDepartmentHistory_ByBusinessEntityID(int businessEntityID) {

          var query = Search(_entities.EmployeeDepartmentHistories, x => x.BusinessEntityID == businessEntityID).Select(ProjectToModel);

            return query;
        }
        
        public IQueryable<EmployeeDepartmentHistoryModel> GetEmployeeDepartmentHistory_ByDepartmentID(short departmentID) {

          var query = Search(_entities.EmployeeDepartmentHistories, x => x.DepartmentID == departmentID).Select(ProjectToModel);

            return query;
        }
        
        public IQueryable<EmployeeDepartmentHistoryModel> GetEmployeeDepartmentHistory_ByShiftID(byte shiftID) {

          var query = Search(_entities.EmployeeDepartmentHistories, x => x.ShiftID == shiftID).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddEmployeeDepartmentHistory(EmployeeDepartmentHistoryModel model) {
            var matchBusinessEntityID = _entities.Employees.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
            if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.BusinessEntityID) + " '{model.BusinessEntityID}' doesn't exist in the system."}; 
            }

            var matchDepartmentID = _entities.Departments.Where(x => x.DepartmentID.Equals(model.DepartmentID));
            if (!matchDepartmentID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.DepartmentID) + " '{model.DepartmentID}' doesn't exist in the system."}; 
            }

            var matchShiftID = _entities.Shifts.Where(x => x.ShiftID.Equals(model.ShiftID));
            if (!matchShiftID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.ShiftID) + " '{model.ShiftID}' doesn't exist in the system."}; 
            }

           try
           {
                 var entity = _mapper.Map<EmployeeDepartmentHistory>(model);
                _entities.EmployeeDepartmentHistories.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("EmployeeDepartmentHistory added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new EmployeeDepartmentHistoryModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateEmployeeDepartmentHistory(EmployeeDepartmentHistoryModel model) {

          var query = Search(_entities.EmployeeDepartmentHistories, x =>  x.BusinessEntityID == model.BusinessEntityID && x.StartDate == model.StartDate && x.DepartmentID == model.DepartmentID && x.ShiftID == model.ShiftID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("EmployeeDepartmentHistory with _businessEntityID, _startDate, _departmentID, _shiftID = '{0}', '{1}', '{2}', '{3}' doesn't exist.",model.BusinessEntityID, model.StartDate, model.DepartmentID, model.ShiftID)}; 
            }
            var matchBusinessEntityID = _entities.Employees.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
            if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse { RequestMessage = "Foreign Key Violation; " + nameof(model.BusinessEntityID) + string.Format("BusinessEntityID = '{0}' doesn't exist in the system.", model.BusinessEntityID)}; 
            }

            var matchDepartmentID = _entities.Departments.Where(x => x.DepartmentID.Equals(model.DepartmentID));
            if (!matchDepartmentID.Any()) {
              return new BuilderResponse { RequestMessage = "Foreign Key Violation; " + nameof(model.DepartmentID) + string.Format("DepartmentID = '{0}' doesn't exist in the system.", model.DepartmentID)}; 
            }

            var matchShiftID = _entities.Shifts.Where(x => x.ShiftID.Equals(model.ShiftID));
            if (!matchShiftID.Any()) {
              return new BuilderResponse { RequestMessage = "Foreign Key Violation; " + nameof(model.ShiftID) + string.Format("ShiftID = '{0}' doesn't exist in the system.", model.ShiftID)}; 
            }

           try
           {
            EmployeeDepartmentHistory entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("EmployeeDepartmentHistory update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteEmployeeDepartmentHistory(int businessEntityID, System.DateTime startDate, short departmentID, byte shiftID) {
          var query = Search(_entities.EmployeeDepartmentHistories, x => x.BusinessEntityID == businessEntityID&& x.StartDate == startDate&& x.DepartmentID == departmentID&& x.ShiftID == shiftID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("EmployeeDepartmentHistory with _businessEntityID, _startDate, _departmentID, _shiftID = '{0}', '{1}', '{2}', '{3}' doesn't exist.",businessEntityID, startDate, departmentID, shiftID)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.EmployeeDepartmentHistories.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("EmployeeDepartmentHistory deleted with values: '{0}'", JsonConvert.SerializeObject(new EmployeeDepartmentHistoryModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<EmployeeDepartmentHistory> Search(IQueryable<EmployeeDepartmentHistory> query, Expression<Func<EmployeeDepartmentHistory, bool>> filter) {
            return query.Where(filter);
        }
    }
}

