// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using HumanResourcesAPI.Entities;
using HumanResourcesAPI.Models;
using HumanResourcesAPI.Services;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;

namespace HumanResourcesAPI.Services {
    
    
    public class JobCandidateBuilder : IJobCandidateBuilder {
        
        private IDbEntities _entities;
        
        private IMapper _mapper;
        
        private ILoggerManager _logger;
        
        public JobCandidateBuilder(EntitiesContext context, IMapper mapper, ILoggerManager logger) {
            _entities = context;
            _mapper = mapper;
            _logger = logger;
        }
        
        private Expression<Func<JobCandidate, JobCandidateModel>>  ProjectToModel {
            get {
                return entity => _mapper.Map<JobCandidateModel>(entity);
            }
        }
        
        public IQueryable<JobCandidateModel> GetJobCandidates() {
            return _entities.JobCandidates.Select(ProjectToModel);
        }
        
        public IList<ExpandoObject> GetDisplayModels(List<string> propNames) {
            var models = _entities.JobCandidates.Select(ProjectToModel);

            var displayModels = new List<ExpandoObject>();
            foreach (var model in models)
            {
                dynamic displayModel = DynamicHelper.ConvertToExpando(model, propNames);
                displayModels.Add(displayModel);
            }

            return displayModels;
        }
        
        public async Task<BuilderResponse> GetJobCandidate_ByJobCandidateID(int jobCandidateID) {
          var query = await Search(_entities.JobCandidates, x => x.JobCandidateID == jobCandidateID).Select(ProjectToModel)?.ToListAsync();
            if (query.Any()) {
              return new BuilderResponse{ Model = query.Single() }; 
            }
            else {
           return new BuilderResponse { RequestMessage = $"Record Not Found; JobCandidate with jobCandidateID = '{jobCandidateID}' doesn't exist." }; 
            }
        }
        
        public IQueryable<JobCandidateModel> GetJobCandidate_ByBusinessEntityID(int businessEntityID) {

          var query = Search(_entities.JobCandidates, x => x.BusinessEntityID == businessEntityID).Select(ProjectToModel);

            return query;
        }
        
        public async Task<BuilderResponse> AddJobCandidate(JobCandidateModel model) {
            if (model.BusinessEntityID != null) {
                var matchBusinessEntityID = _entities.Employees.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
                if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse { RequestMessage = $"Foreign Key Violation; " + nameof(model.BusinessEntityID) + " '{model.BusinessEntityID}' doesn't exist in the system."}; 
                }
            }

           try
           {
                 var entity = _mapper.Map<JobCandidate>(model);
                _entities.JobCandidates.Add(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("JobCandidate added with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ Model = new JobCandidateModel(entity) }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert explicit value for identity column"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "IDENTITY_INSERT is set to OFF; Cannot insert explicit value for identity column when IDENTITY_INSERT is set to OFF."};
                }
                else if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> UpdateJobCandidate(JobCandidateModel model) {

          var query = Search(_entities.JobCandidates, x =>  x.JobCandidateID == model.JobCandidateID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("JobCandidate with _jobCandidateID = '{0}' doesn't exist.",model.JobCandidateID)}; 
            }
            if (model.BusinessEntityID != null) {
                var matchBusinessEntityID = _entities.Employees.Where(x => x.BusinessEntityID.Equals(model.BusinessEntityID));
                if (!matchBusinessEntityID.Any()) {
              return new BuilderResponse{ RequestMessage = "Foreign Key Violation; " + nameof(model.BusinessEntityID) + string.Format("JobCandidate with BusinessEntityID = '{0}' doesn't exist.", model.BusinessEntityID)}; 
                }
            }

           try
           {
            JobCandidate entity = query.SingleOrDefault();
             entity = model.ToEntity(entity);
               await _entities.SaveChangesAsync();
                _logger.LogInfo(string.Format("JobCandidate update with values: '{0}'", JsonConvert.SerializeObject(model)));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.Created }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("Cannot insert duplicate key row"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + Environment.NewLine + JsonConvert.SerializeObject(model) + Environment.NewLine + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Duplicate exception; Please verify that an item with these values doesn't already exists."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        public async Task<BuilderResponse> DeleteJobCandidate(int jobCandidateID) {
          var query = Search(_entities.JobCandidates, x => x.JobCandidateID == jobCandidateID);
            if (!query.Any()) {
              return new BuilderResponse { RequestMessage = "Record Not Found; " + string.Format("JobCandidate with _jobCandidateID = '{0}' doesn't exist.",jobCandidateID)}; 
            }
            var entity = query.SingleOrDefault();

           try
           {
                _entities.JobCandidates.Remove(entity);
               await _entities.SaveChangesAsync();
            _logger.LogInfo(string.Format("JobCandidate deleted with values: '{0}'", JsonConvert.SerializeObject(new JobCandidateModel(entity))));
               return new BuilderResponse{ StatusCode = (int)HttpStatusCode.NoContent }; 
            }
            catch (DbUpdateException ue)
            {
                if(ue.InnerException != null && ue.InnerException.Message.Contains("The DELETE statement conflicted with the REFERENCE constraint"))
                {
                    var inner = ue.InnerException;
                    _logger.LogError(inner.Message + inner.StackTrace);
                    return new BuilderResponse { ErrorMessage = "Please delete related items first."};
                }
                _logger.LogError(ue.Message + ue.StackTrace);
                return new BuilderResponse { ErrorMessage = ue.Message };
            }
            catch (Exception e)
            {
                _logger.LogError(e.Message + e.StackTrace);
                return new BuilderResponse { ErrorMessage = e.Message};
            }
        }
        
        private IQueryable<JobCandidate> Search(IQueryable<JobCandidate> query, Expression<Func<JobCandidate, bool>> filter) {
            return query.Where(filter);
        }
    }
}

