// ----------------------------------------------------------------------------------
// <copyright company="Exesoft Inc.">
//	This code was generated by Instant Web API code automation software (https://www.InstantWebAPI.com)
//	Copyright Exesoft Inc. © 2019.  All rights reserved.
// </copyright>
// ----------------------------------------------------------------------------------

using AutoMapper;
using HumanResourcesAPI.Entities;

namespace HumanResourcesAPI.Models {
    
    
    public class AutoMapperProfiles : Profile {
        
        public AutoMapperProfiles() {
            CreateMap<Department, DepartmentModel>();
            CreateMap<DepartmentModel, Department>();
            CreateMap<Employee, EmployeeModel>();
            CreateMap<EmployeeModel, Employee>();
            CreateMap<EmployeeDepartmentHistory, EmployeeDepartmentHistoryModel>();
            CreateMap<EmployeeDepartmentHistoryModel, EmployeeDepartmentHistory>();
            CreateMap<EmployeePayHistory, EmployeePayHistoryModel>();
            CreateMap<EmployeePayHistoryModel, EmployeePayHistory>();
            CreateMap<JobCandidate, JobCandidateModel>();
            CreateMap<JobCandidateModel, JobCandidate>();
            CreateMap<Shift, ShiftModel>();
            CreateMap<ShiftModel, Shift>();
        }
    }
}

